name: GitHub Maven Build Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build Maven Project
        run: mvn -B clean package --file pom.xml

      - name: STEP 4 - List Files
        run: |
          Get-ChildItem -Force
          cd target
          Get-ChildItem -Force
